# https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
apiVersion: v1
kind: Secret
metadata:
  name: rapidly-tls
  namespace: rapidlink
type: kubernetes.io/tls
# The TLS secret must contain keys named 'tls.crt' and 'tls.key' that contain the certificate and private key to use for TLS.
data:
  tls.crt: base64 encoded public key content
  tls.key: base64 encoded private key content